# Generated by Django 4.1.13 on 2024-07-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_accepted_at_appointment_rejected_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
