# Generated by Django 4.1.13 on 2024-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_notification_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
